### ISSUE TITLE
Syntax for codeBlock is not mentioned

### ISSUE THREAD

**Issue by VenkataBhaskarr** [ralsina/rst-cheatsheet#23]
<img width="512" alt="Screenshot 2022-11-25 at 2 19 06 PM" src="https://user-images.githubusercontent.com/111889155/203939658-cfb48a12-5bce-41e1-baa8-67522a7f7c57.png">

<img width="1026" alt="Screenshot 2022-11-25 at 2 19 16 PM" src="https://user-images.githubusercontent.com/111889155/203939649-6eef6233-96eb-434a-9132-4eaf245a2f21.png">

**Comment by ralsina** [comment]
This predates code blocks :-)
