### ISSUE TITLE
Inline internal target does not work

### ISSUE THREAD

**Issue by ezyang** [ralsina/rst-cheatsheet#7]
If you look at the generated HTML the inline target doesn't actually get an id generated for it.

**Comment by ralsina** [comment]
If you can fix it and do a PR, much appreciated, I don't really have time to look into this these days :-)

**Comment by ezyang** [comment]
Well, I have no idea how to do this in GitHub RST! Sounds impossible. Best to just remove the entry, or add a note it doesn't work.

**Comment by ekevoo** [comment]
I've tried to come up with a PR to no avail. As far as I can tell, GitHub
definitely does not support it.

https://gist.github.com/ekevoo/1f939b669388c54fea54b62b7ec1f309

**Comment by ralsina** [comment]
This seems to be a problem with rst as processed by GH and not with the official implementation, closing.

**Comment by Liz4v** [comment]
By the way, it has been implemented sometime in the past 5 years, so it works now!
